version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - my-network

  kafka-server:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-server
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - my-network
    depends_on:
      - zookeeper

  minecraft:
    # Container Image on dockerhub 
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    # Port Mappings
    ports:
      - "25565:25565"
    # Environment Variables
    environment:
      EULA: "TRUE"
    volumes:
      - type: bind
        source: C:\Users\cgrey\Documents\mc_data_proto
        target: /data
    #Optional, was just trying to limit some memory/cpu usage on my machine
    deploy:
      resources:
        limits:
          cpus: "1" #allowed 1 cpu core of time
          memory: "3g"
    networks:
      - my-network

  kafka-producer:
    build: ./mc_producer
    container_name: kafka-producer-mc
    working_dir: /app
    volumes:
      - minecraft_data:/minecraft_logs
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    networks:
      - my-network
    depends_on:
      - kafka-server
      - minecraft

  kafka-producer-docker-metrics:
    build: ./docker_metrics_producer
    container_name: kafka-producer-docker-metrics
    working_dir: /app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    networks:
      - my-network
    depends_on:
      - kafka-server
      - minecraft

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-proto
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --log.level=debug
    #NOT persistent on docker down you will loose all stats
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/prometheus_alert_rules.yml:/etc/prometheus/alert_rules.yml
    networks:
      - my-network
    depends_on:
    - cadvisor

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - my-network

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor-proto
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    networks:
      - my-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-proto
    restart: unless-stopped
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      #is persistent so we dont loose dashboards we made
      - type: bind
        source: C:\Users\cgrey\Documents\grafana_proto
        target: /var/lib/grafana
    networks:
      - my-network
    depends_on:
    - prometheus
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
  connect:
    image: debezium/connect:1.3
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka-server:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    networks:
      - my-network
    depends_on:
      - kafka-producer-docker-metrics
      - mongodb
networks:
  my-network:
    driver: bridge

volumes:
  minecraft_data:
    driver: local
  grafana-storage: {}