
#Handlers settings
[handlers]
	#Enable colorizing Banner using one of valid dyes
	banner = true
	#Enable colorizing Bed using one of valid dyes
	bed = true
	#Enable colorizing Candle using one of valid dyes
	candle = true
	#Enable colorizing Carpet using one of valid dyes
	carpet = true
	#Enable colorizing Concrete using one of valid dyes
	concrete = true
	#Enable colorizing Concrete Powder using one of valid dyes
	concretePowder = true
	#Enable colorizing Glazed Terracotta using one of valid dyes
	glazedTerracotta = true
	#Enable colorizing Shulker Box using one of valid dyes
	shulkerBox = true
	#Enable colorizing Stained Glass using one of valid dyes
	stainedGlass = true
	#Enable colorizing Stained Glass Pane using one of valid dyes
	stainedGlassPane = true
	#Enable colorizing Terracotta using one of valid dyes
	terracotta = true
	#Enable colorizing Wool using one of valid dyes
	wool = true
	#Enable colorizing Mossy Cobblestone to Mossy variant using Vines
	mossyCobblestone = true
	#Enable colorizing Mossy Cobblestone Slab to Mossy variant using Vines
	mossyCobblestoneSlab = true
	#Enable colorizing Mossy Cobblestone Stairs to Mossy variant using Vines
	mossyCobblestoneStairs = true
	#Enable colorizing Mossy Cobblestone Wall to Mossy variant using Vines
	mossyCobblestoneWall = true
	#Enable colorizing Mossy Stone Bricks to Mossy variant using Vines
	mossyStoneBricks = true
	#Enable colorizing Mossy Stone Brick Slab to Mossy variant using Vines
	mossyStoneBrickSlab = true
	#Enable colorizing Mossy Stone Brick Stairs to Mossy variant using Vines
	mossyStoneBrickStairs = true
	#Enable colorizing Mossy Stone Brick Wall to Mossy variant using Vines
	mossyStoneBrickWall = true

#Sneaking settings
[sneaking]
	#Require sneaking for colorizing Banner
	banner = false
	#Require sneaking for colorizing Bed
	bed = false
	#Require sneaking for colorizing Candle
	candle = false
	#Require sneaking for colorizing Carpet
	carpet = false
	#Require sneaking for colorizing Concrete
	concrete = false
	#Require sneaking for colorizing Concrete Powder
	concretePowder = false
	#Require sneaking for colorizing Glazed Terracotta
	glazedTerracotta = false
	#Require sneaking for colorizing Shulker Box
	shulkerBox = false
	#Require sneaking for colorizing Stained Glass
	stainedGlass = false
	#Require sneaking for colorizing Stained Glass Pane
	stainedGlassPane = false
	#Require sneaking for colorizing Terracotta
	terracotta = false
	#Require sneaking for colorizing Wool
	wool = false
	#Require sneaking for colorizing Mossy Cobblestone
	mossyCobblestone = true
	#Require sneaking for colorizing Mossy Cobblestone Slab
	mossyCobblestoneSlab = true
	#Require sneaking for colorizing Mossy Cobblestone Stairs
	mossyCobblestoneStairs = true
	#Require sneaking for colorizing Mossy Cobblestone Wall
	mossyCobblestoneWall = true
	#Require sneaking for colorizing Mossy Stone Bricks
	mossyStoneBricks = true
	#Require sneaking for colorizing Mossy Stone Brick Slab
	mossyStoneBrickSlab = true
	#Require sneaking for colorizing Mossy Stone Brick Stairs
	mossyStoneBrickStairs = true
	#Require sneaking for colorizing Mossy Stone Brick Wall
	mossyStoneBrickWall = true

#Consume item settings
[consume]
	#Enable consuming item when colorizing Banner
	banner = true
	#Enable consuming item when colorizing Bed
	bed = true
	#Enable consuming item when colorizing Candle
	candle = true
	#Enable consuming item when colorizing Carpet
	carpet = true
	#Enable consuming item when colorizing Concrete
	concrete = true
	#Enable consuming item when colorizing Concrete Powder
	concretePowder = true
	#Enable consuming item when colorizing Glazed Terracotta
	glazedTerracotta = true
	#Enable consuming item when colorizing Shulker Box
	shulkerBox = true
	#Enable consuming item when colorizing Stained Glass
	stainedGlass = true
	#Enable consuming item when colorizing Stained Glass Pane
	stainedGlassPane = true
	#Enable consuming item when colorizing Terracotta
	terracotta = true
	#Enable consuming item when colorizing Wool
	wool = true
	#Enable consuming item when colorizing Mossy Cobblestone
	mossyCobblestone = true
	#Enable consuming item when colorizing Mossy Cobblestone Slab
	mossyCobblestoneSlab = true
	#Enable consuming item when colorizing Mossy Cobblestone Stairs
	mossyCobblestoneStairs = true
	#Enable consuming item when colorizing Mossy Cobblestone Wall
	mossyCobblestoneWall = true
	#Enable consuming item when colorizing Mossy Stone Bricks
	mossyStoneBricks = true
	#Enable consuming item when colorizing Mossy Stone Brick Slab
	mossyStoneBrickSlab = true
	#Enable consuming item when colorizing Mossy Stone Brick Stairs
	mossyStoneBrickStairs = true
	#Enable consuming item when colorizing Mossy Stone Brick Wall
	mossyStoneBrickWall = true

