#alertmanager.yml
global:
  resolve_timeout: 1m
route:
  receiver: discord
receivers:
    - name: discord
      discord_configs:
        - webhook_url: 'https://discord.com/api/webhooks/1261426821799477311/xcFC_PHbEl9WcvyLyeqS93U2IkMUWblEjur7HQymplV7jiHVmHwrE6vcAd-LkjT0miuI'
          send_resolved: false