global:
  scrape_interval: 5s
rule_files:
  - alert_rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
