global:
  scrape_interval: 10s
  evaluation_interval: 5s
rule_files:
  - alert_rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080
  - job_name: synthetic-metric
    static_configs:
      - targets:
        - syntheticmetrics:9999
  - job_name: 'minecraft'
    static_configs:
      - targets: 
        - minecraft:19565  # Replace with your Minecraft server's container name and port
  - job_name: 'kafka-server'
    static_configs:
      - targets: 
        - kafka-server:9092
